//
// Created by Alie on 11/1/2020.
//

#ifndef PROJECT4_HIGHESTPRIORITY_PATIENTPRIORITYQUEUE_H
#define PROJECT4_HIGHESTPRIORITY_PATIENTPRIORITYQUEUE_H


class PatientPriorityQueue {

};


#endif //PROJECT4_HIGHESTPRIORITY_PATIENTPRIORITYQUEUE_H
